In [2]:
from rdflib import Graph, Namespace
import pandas as pd

ns = Namespace("http://n4d.sh/civ6#")

# Загрузите онтологию
g = Graph()
g.parse("civ6-ontology-v2.rdf", format="xml")

In [3]:
def run_sparql_query(query, graph):
    """
    Executes a SPARQL query and returns results as a pandas DataFrame.
    """
    results = graph.query(query)
    data = []

    for row in results:
        data.append(
            {var: row[var] for var in row.labels}
        )  # Collect variables and their values

    return pd.DataFrame(data)

Отобразим найденных с помощью wikidata лидеров

In [4]:
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://n4d.sh/civ6#>

SELECT ?entity ?name ?civilizationName
WHERE {
  ?entity :source "wikidata" ;
          :name ?name .
  OPTIONAL {
    ?entity :rules ?civilization .
    ?civilization :name ?civilizationName .
  }
}
"""

run_sparql_query(query, g)

,entity,name,civilizationName
0,http://n4d.sh/civ6#Gorgo,Gorgo,Greece
1,http://n4d.sh/civ6#Gorgo,Gorgo,Sparta
2,http://n4d.sh/civ6#John_Curtin,John Curtin,Australia
3,http://n4d.sh/civ6#Victoria,Victoria,England
4,http://n4d.sh/civ6#Victoria,Victoria,United Kingdom of Great Britain and Ireland
5,http://n4d.sh/civ6#Hedwig_of_Silesia,Hedwig of Silesia,Holy Roman Empire
6,http://n4d.sh/civ6#Tomyris,Tomyris,Scythia
7,http://n4d.sh/civ6#Tomyris,Tomyris,Massagetae
8,http://n4d.sh/civ6#Hōjō_Tokimune,Hōjō Tokimune,Japan
9,http://n4d.sh/civ6#Frédéric_Barberousse,Frédéric Barberousse,Holy Roman Empire
10,http://n4d.sh/civ6#Theodore_Roosevelt,Theodore Roosevelt,America
11,http://n4d.sh/civ6#Theodore_Roosevelt,Theodore Roosevelt,United States
12,http://n4d.sh/civ6#Jayavarman_VII,Jayavarman VII,Khmer
13,http://n4d.sh/civ6#Pericles,Pericles,Greece
14,http://n4d.sh/civ6#Pericles,Pericles,Classical Athens
15,http://n4d.sh/civ6#Cyrus_the_Great,Cyrus the Great,Achaemenid Empire
16,http://n4d.sh/civ6#Cyrus_the_Great,Cyrus the Great,Anshan Persia
17,http://n4d.sh/civ6#Peter_the_Great,Peter the Great,Tsardom of Russia
18,http://n4d.sh/civ6#Peter_the_Great,Peter the Great,Russian Empire
19,http://n4d.sh/civ6#Trajan,Trajan,Rome
20,http://n4d.sh/civ6#Trajan,Trajan,Ancient Rome
21,http://n4d.sh/civ6#Amanitore,Amanitore,Nubia
22,http://n4d.sh/civ6#Amanitore,Amanitore,Kush
23,http://n4d.sh/civ6#Catherine_de'_Medici,Catherine de' Medici,France
24,http://n4d.sh/civ6#Pedro_II_of_Brazil,Pedro II of Brazil,Brazil
25,http://n4d.sh/civ6#Afonso_I_of_Kongo,Afonso I of Kongo,Kingdom of Kongo
26,http://n4d.sh/civ6#Alexander_the_Great,Alexander the Great,Macedonia
27,http://n4d.sh/civ6#Saladin,Saladin,Arabia
28,http://n4d.sh/civ6#Tribhuwana_Wijayatunggadewi,Tribhuwana Wijayatunggadewi,None
29,http://n4d.sh/civ6#Harald_III_of_Norway,Harald III of Norway,Kingdom of Norway
30,http://n4d.sh/civ6#Cleopatra,Cleopatra,Ptolemaic Kingdom
31,http://n4d.sh/civ6#Moctezuma_I,Moctezuma I,None
32,http://n4d.sh/civ6#Philip_II_of_Spain,Philip II of Spain,Kingdom of Portugal
33,http://n4d.sh/civ6#Philip_II_of_Spain,Philip II of Spain,Spain

In [5]:
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://n4d.sh/civ6#>

SELECT ?leader ?name
WHERE {
  ?leader a :Leader ;
          :name ?name ;
          :rules "None" .
}
"""

run_sparql_query(query, g)[0:10]

                                           leader                         name
0               http://n4d.sh/civ6#Jayavarman_VII               Jayavarman VII
1                      http://n4d.sh/civ6#Saladin                      Saladin
2  http://n4d.sh/civ6#Tribhuwana_Wijayatunggadewi  Tribhuwana Wijayatunggadewi
3                  http://n4d.sh/civ6#Moctezuma_I                  Moctezuma I

In [8]:
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://n4d.sh/civ6#>

SELECT ?religion (COUNT(DISTINCT ?civilization) AS ?civilization_count)
WHERE {
  ?leader a :Leader ;
          :rules ?civilization ;
          :believesIn ?religion .
}
GROUP BY ?religion
ORDER BY DESC(?civilization_count)
"""

run_sparql_query(query, g).head(5)

                               religion civilization_count
0        http://n4d.sh/civ6#Catholicism                 12
1      http://n4d.sh/civ6#Protestantism                  7
2           http://n4d.sh/civ6#Buddhism                  6
3  http://n4d.sh/civ6#Eastern_Orthodoxy                  5
4              http://n4d.sh/civ6#Islam                  5